use super::copy_utility;
use super::save_target::SaveTarget;
use crate::error::PbrtError;
use crate::io::pbrt::ParseTarget;
use crate::model::base::Matrix4x4;
use crate::model::base::ParamSet;
use crate::model::base::Vector3;
use crate::model::scene::CameraComponent;
use crate::model::scene::CameraProperties;
use crate::model::scene::FilmComponent;
use crate::model::scene::IntegratorComponent;
use crate::model::scene::IntegratorProperties;
use crate::model::scene::Material;
use crate::model::scene::Node;
use crate::model::scene::OptionProperties;
use crate::model::scene::PropertyEntry;
use crate::model::scene::ResourceComponent;
use crate::model::scene::SamplerComponent;
use crate::model::scene::SamplerProperties;
use crate::model::scene::TransformComponent;

use std::fs::File;
use std::io::Write;
use std::path::Path;
use std::sync::Arc;
use std::sync::RwLock;

#[derive(Debug, Clone)]
pub struct SavePbrtOptions {
    pub pretty_print: bool,
    pub copy_resources: bool,
}

impl Default for SavePbrtOptions {
    fn default() -> Self {
        Self {
            pretty_print: true,
            copy_resources: true,
        }
    }
}

struct PbrtSaver<W: Write> {
    target: SaveTarget<W>,
    options: SavePbrtOptions,
}

fn get_world_matrix(node: &Arc<RwLock<Node>>) -> Result<Matrix4x4, PbrtError> {
    let node = node.read().unwrap();
    if let Some(parent) = node.parent.as_ref() {
        let parent = parent.upgrade().unwrap();
        let parent_matrix = get_world_matrix(&parent)?;
        let local_matrix = node
            .get_component::<TransformComponent>()
            .ok_or(PbrtError::error("Transform is not found!"))?;
        return Ok(parent_matrix * local_matrix.get_local_matrix());
    } else {
        let local_matrix = node
            .get_component::<TransformComponent>()
            .ok_or(PbrtError::error("Transform is not found!"))?;
        return Ok(local_matrix.get_local_matrix());
    }
}

fn near_equal(a: f32, b: f32, epsilon: f32) -> bool {
    (a - b).abs() < epsilon
}

fn apply_transform(
    transform: &Matrix4x4,
    target: &mut dyn ParseTarget,
) -> Result<(), PbrtError> {
    let (t, r, s) = transform
        .decompose(0.1)
        .ok_or(PbrtError::error("Decompose failed!"))?;
    if !near_equal(t.x, 0.0, 1e-6) || !near_equal(t.y, 0.0, 1e-6) || !near_equal(t.z, 0.0, 1e-6) {
        target.translate(t.x, t.y, t.z);
    }
    if !near_equal(r.w.abs(), 1.0, 1e-6) {
        let theta = (2.0 * f32::acos(r.w)).to_degrees();
        let axis = Vector3::new(r.x, r.y, r.z).normalize();
        target.rotate(theta, axis.x, axis.y, axis.z);
    }
    if !near_equal(s.x, 1.0, 1e-6) || !near_equal(s.y, 1.0, 1e-6) || !near_equal(s.z, 1.0, 1e-6) {
        target.scale(s.x, s.y, s.z);
    }
    Ok(())
}

fn _get_material_ignore_keys(material: &Material) -> Vec<String> {
    let mut ignore_keys = Vec::new();
    if material.get_type() == "subsurface"
        && let Some(name_value) = material.props.find_one_string("string name")
        && !name_value.is_empty()
    {
        ignore_keys.push("sigma_a".to_string());
        ignore_keys.push("sigma_s".to_string());
    }
    ignore_keys
}

impl<W: Write> PbrtSaver<W> {
    pub fn new(writer: W, options: &SavePbrtOptions) -> Self {
        let target = SaveTarget::new(writer, options.pretty_print);
        PbrtSaver {
            target,
            options: options.clone(),
        }
    }

    fn collect_params_from_entries(
        &self,
        entries: &[PropertyEntry],
        props: &ParamSet,
    ) -> ParamSet {
        let mut params = ParamSet::new();
        for entry in entries.iter() {
            if !entry.output_to_file {
                continue;
            }
            if let Some((_kt, _kn, value)) = props.entry(&entry.key_name) {
                params.insert(&format!("{} {}", entry.key_type, entry.key_name), value.clone());
            }
        }
        params
    }

    fn write_header(
        &mut self,
        _node: &Arc<RwLock<Node>>,
    ) -> Result<(), PbrtError> {
        writeln!(self.target.writer, "# Generated by pbrt-ui")?;
        Ok(())
    }

    fn write_camera_options(
        &mut self,
        node: &Arc<RwLock<Node>>,
    ) -> Result<(), PbrtError> {
        let camera_node = Node::find_node_by_component::<CameraComponent>(node)
            .ok_or(PbrtError::error("Camera is not found!"))?;
        
        // Camera Transform
        {
            let local_to_world = get_world_matrix(&camera_node)?;
            let world_to_local = local_to_world
                .inverse()
                .ok_or(PbrtError::error("Camera transform is not found!"))?;
            apply_transform(&world_to_local, &mut self.target)?;
        }
        
        // Camera
        {
            let camera_node = camera_node.read().unwrap();
            let camera_component = camera_node
                .get_component::<CameraComponent>()
                .ok_or(PbrtError::error("Camera is not found!"))?;
            let camera_type = camera_component
                .props
                .find_one_string("string type")
                .ok_or(PbrtError::error("Camera type is not found!"))?;
            let camera_properties = CameraProperties::get_instance();
            if let Some(entries) = camera_properties.get_entries(&camera_type) {
                let params = self.collect_params_from_entries(entries, &camera_component.props);
                self.target.camera(&camera_type, &params);
            }
        }
        
        // Film
        {
            let camera_node = camera_node.read().unwrap();
            let film_component = camera_node
                .get_component::<FilmComponent>()
                .ok_or(PbrtError::error("Film is not found!"))?;
            let film_type = film_component
                .props
                .find_one_string("string type")
                .ok_or(PbrtError::error("Film type is not found!"))?;
            let option_properties = OptionProperties::get_instance();
            if let Some(entries) = option_properties.get_entries("film") {
                let params = self.collect_params_from_entries(entries, &film_component.props);
                self.target.film(&film_type, &params);
            }
        }
        
        Ok(())
    }

    fn write_sampler_options(
        &mut self,
        node: &Arc<RwLock<Node>>,
    ) -> Result<(), PbrtError> {
        let node = node.read().unwrap();
        let sampler_component = node
            .get_component::<SamplerComponent>()
            .ok_or(PbrtError::error("Sampler is not found!"))?;
        let sampler_type = sampler_component
            .props
            .find_one_string("string type")
            .ok_or(PbrtError::error("Sampler type is not found!"))?;
        let sampler_properties = SamplerProperties::get_instance();
        if let Some(entries) = sampler_properties.get_entries(&sampler_type) {
            let params = self.collect_params_from_entries(entries, &sampler_component.props);
            self.target.sampler(&sampler_type, &params);
        }
        Ok(())
    }

    fn write_integrator_options(
        &mut self,
        node: &Arc<RwLock<Node>>,
    ) -> Result<(), PbrtError> {
        let node = node.read().unwrap();
        let integrator_component = node
            .get_component::<IntegratorComponent>()
            .ok_or(PbrtError::error("Integrator is not found!"))?;
        let integrator_type = integrator_component
            .props
            .find_one_string("string type")
            .ok_or(PbrtError::error("Integrator type is not found!"))?;
        let integrator_properties = IntegratorProperties::get_instance();
        if let Some(entries) = integrator_properties.get_entries(&integrator_type) {
            let params = self.collect_params_from_entries(entries, &integrator_component.props);
            self.target.integrator(&integrator_type, &params);
        }
        Ok(())
    }

    fn write_options_block(
        &mut self,
        node: &Arc<RwLock<Node>>,
    ) -> Result<(), PbrtError> {
        self.write_camera_options(node)?;
        if self.options.pretty_print {
            writeln!(self.target.writer)?;
        }
        self.write_sampler_options(node)?;
        if self.options.pretty_print {
            writeln!(self.target.writer)?;
        }
        self.write_integrator_options(node)?;
        if self.options.pretty_print {
            writeln!(self.target.writer)?;
        }
        Ok(())
    }

    fn write_world_block(
        &mut self,
        _node: &Arc<RwLock<Node>>,
    ) -> Result<(), PbrtError> {
        self.target.world_begin();
        // TODO: Implement texture, material, and geometry writing
        // self.write_textures(node)?;
        // self.write_materials(node)?;
        // self.write_geometries(node)?;
        self.target.world_end();
        Ok(())
    }

    fn copy_resources(
        &self,
        node: &Arc<RwLock<Node>>,
        path: &str,
    ) -> Result<(), PbrtError> {
        if !self.options.copy_resources {
            return Ok(());
        }

        let out_dir = Path::new(path).parent().ok_or(PbrtError::error(
            "Failed to get parent directory!",
        ))?;
        let node = node.read().unwrap();
        if let Some(resources_component) = node.get_component::<ResourceComponent>() {
            let resource_manager = resources_component.get_resource_manager();
            let resource_manager = resource_manager.read().unwrap();
            let mut copy_paths = Vec::new();

            // Copy textures
            for (_id, texture) in resource_manager.textures.iter() {
                let texture = texture.read().unwrap();
                let texture_type = texture.get_type();
                if texture_type != "imagemap" {
                    continue;
                }
                let filename = texture.get_filename();
                let fullpath = texture.get_fullpath();
                if let (Some(filename), Some(fullpath)) = (filename, fullpath) {
                    let src_path = Path::new(&fullpath).to_path_buf();
                    let dst_path = out_dir.join(filename);
                    if src_path != dst_path && src_path.exists() {
                        copy_paths.push((src_path, dst_path));
                    }
                }
            }

            // Copy meshes
            for (_id, mesh) in resource_manager.meshes.iter() {
                let mesh = mesh.read().unwrap();
                let mesh_type = mesh.get_type();
                if mesh_type != "plymesh" {
                    continue;
                }
                let filename = mesh.get_filename();
                let fullpath = mesh.get_fullpath();
                if let (Some(filename), Some(fullpath)) = (filename, fullpath) {
                    let src_path = Path::new(&fullpath).to_path_buf();
                    let dst_path = out_dir.join(filename);
                    if src_path != dst_path && src_path.exists() {
                        copy_paths.push((src_path, dst_path));
                    }
                }
            }

            // Copy other resources
            for (_id, other_resource) in resource_manager.other_resources.iter() {
                let other_resource = other_resource.read().unwrap();
                let filename = other_resource.get_filename();
                let fullpath = other_resource.get_fullpath();
                if let (Some(filename), Some(fullpath)) = (filename, fullpath) {
                    let src_path = Path::new(&fullpath).to_path_buf();
                    let dst_path = out_dir.join(filename);
                    if src_path != dst_path && src_path.exists() {
                        copy_paths.push((src_path, dst_path));
                    }
                }
            }

            for (src_path, dst_path) in copy_paths.iter() {
                if let Err(e) = copy_utility::copy_file(src_path, dst_path) {
                    log::warn!(
                        "Failed to copy resource from {:?} to {:?}: {}",
                        src_path, dst_path, e
                    );
                }
            }
        }
        Ok(())
    }

    pub fn write(&mut self, node: &Arc<RwLock<Node>>, path: &str) -> Result<(), PbrtError> {
        self.write_header(node)?;
        self.write_options_block(node)?;
        if self.options.pretty_print {
            writeln!(self.target.writer)?;
        }
        self.write_world_block(node)?;
        self.copy_resources(node, path)?;
        Ok(())
    }
}

pub fn save_pbrt(
    node: &Arc<RwLock<Node>>,
    path: &str,
    options: &SavePbrtOptions,
) -> Result<(), PbrtError> {
    let file = File::create(path)?;
    let writer = std::io::BufWriter::new(file);
    let mut pbrt_writer = PbrtSaver::new(writer, options);
    pbrt_writer.write(node, path)?;
    Ok(())
}
